### ISSUE TITLE
Registrierungs API lässt update von Benutzerdaten zu

### ISSUE THREAD

**Issue by leonschbbht** [FAP-Cloud-Service/FAP-Backend#45]
Wird ein Benutzer über den `/api/users/new`-Endpunkt angelegt, der bereits existiert werden die Anfrage akzeptiert und die bestehenden Daten werden überschrieben.

Das ist ein Sicherheitsrisiko weil ich alle Daten meiner 'Freunde' ändern könnte, solange ich den Benutzernamen kenne.

**Comment by maltemorgenstern** [comment]
Wurde durch #33 gelöst, Deployment steht noch aus.
