### ISSUE TITLE
Könnt ihr die Passwörter bitte gehashed speichern? DANKE!

### ISSUE THREAD

**Issue by leonschbbht** [FAP-Cloud-Service/FAP-Backend#53]

**Comment by maltemorgenstern** [comment]
Aktuell sind leider keine Kapazitäten frei, wird im nächsten Jahr angegangen.

**Comment by leonschbbht** [comment]
Ist das hier Microsoft oder was?

**Comment by Mindia620** [comment]
Nein Star Citizen, pushed and deleted from Roadmap
